account/urls.py
from django.urls import path
from . import views
from .views import *
from django.contrib.auth.views import LogoutView

app_name = "account"
urlpatterns = [
    path('register/', views.Registration, name='register'),
    path('update-user/<str:pk>/', views.UpdateUser, name='updateuser'),
    path('registry/', views.UserRegistry, name='registry'),
    path('user-details/<str:pk>/', views.UserDetails, name='userdetails'),
    path('login/', CreateLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('delete-user/<str:pk>/', views.DeleteUser, name='deleteuser'),
]

barbados/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls", namespace="base")),
    path("account-app/", include("account.urls", namespace="account")),
    path("truck-app/", include("trucks.urls", namespace="trucks")),
    path("driver-app/", include("drivers.urls", namespace="drivers")),
    path("order-app/", include("orders.urls", namespace="orders")),
    path("trip-app/", include("trips.urls", namespace="trips")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/urls.py
from django.urls import path
from trips import views
from . import views
app_name="base"
urlpatterns = [
    path('', views.home, name='index'),
]

orders/urls.py
from django.urls import path
from . import views

app_name="orders"
urlpatterns=[

    path('addcompanyorder/', views.AddCompanyOrder, name='companyorder'),
    path('update-companyorder/<str:pk>/', views.UpdateCompanyOrder, name='updatecompanyorder'),
    path('viewcompanyorder/', views.ViewCompanyOrder, name='viewcompanyorder'),
    path('companyorderdetails/<str:pk>/', views.CompanyOrderDetails, name='companyorderdetail'),
    path('addindividualorder/', views.AddIndivdualOrder, name='individualorder'),
    path('update-individualorder/<str:pk>/', views.UpdateIndividualOrder, name='updateindividualorder'),
    path('viewindividualorder/', views.ViewIndividualOrder, name='viewindividualorder'),
    path('individualorderdetails/<str:pk>/', views.IndividualOrderDetails, name='individualorderdetail'),
    path('idelete/<str:pk>/', views.DeleteIOrder, name='idelete'),
    path('cdelete/<str:pk>/', views.DeleteCOrder, name='cdelete'),
    
]

trips/urls.py
from django.urls import path
from . import views

app_name = "trips"

urlpatterns = [
    path("add-Itrip/", views.IndividualTripForm, name="individualtrip"),
    path("view-Itrip/", views.IndividualTripView, name="viewindividualtrip"),
    path("update-Itrip/<str:pk>/", views.ITripUpdate, name="updateindividualtrip"),
    path("delete-Itrip/<str:pk>/", views.DeleteItrip, name="deleteindividualtrip"),
    path("update-Ctrip/<str:pk>/", views.CTripUpdate, name="updatecompanytrip"),
    path("add-Ctrip/", views.CompanyTripForm, name="companytrip"),
    path("view-Ctrip/", views.CompanyTripView, name="viewcompanytrip"),
    path("delete-Ctrip/<str:pk>/", views.DeleteCtrip, name="deletecompanytrip"),
    path('view-trip-corders/<str:ctrip>/', views.ctrip_order, name='ctorders'),
    path('view-trip-iorders/<str:itrip>/', views.itrip_order, name='itorders'),
    path('print-corders/<str:cprint>/', views.print_ctrip_order, name='cprint'),
    path('print-iorders/<str:iprint>/', views.print_itrip_order, name='iprint'),
    
]

trucks/urls.py
from django.urls import path
from . import views
app_name="trucks"
urlpatterns = [
    path('add-truck/', views.AddTruck, name='truck'),
    path('update-truck/<str:pk>/', views.UpdateTruck, name='updatetruck'),
    path('delete-truck/<str:delete>/', views.DeleteTruck, name='deletetruck'),
]

base/models.py
from django.db import models

# Create your models here.
class Name(models.Model):
    ID = (("DL", "Driver's License"), ("IP", "Int'l Passport"), ("NI", "NIN"))
    first_name = models.CharField(max_length=30, help_text="Enter First Name", blank=False, null=False)
    last_name = models.CharField(max_length=30, help_text="Enter SurName e.g Father's Name", blank=False, null=False)
    middle_name = models.CharField(
        max_length=30,default="" ,help_text="Enter Middle Name", blank=True, null=True
    )
    id_type = models.CharField(max_length=3, choices=ID)
    id_number = models.CharField(max_length=12)
    phone_number = models.CharField(
        max_length=11, help_text="Enter representative's Phone Number, 11 digits"
    )
    class Meta:
        abstract = True

    @property
    def fullname(self):
        if self.middle_name is None:
            return f"{self.first_name} {self.last_name}"
        else:
            return f"{self.first_name} {self.middle_name} {self.last_name}"

base/views.py
from django.shortcuts import render, redirect
from trucks.models import *
from orders.models import *
from trips.models import *
from django.contrib.auth.decorators import login_required


@login_required(login_url='account:login')
def home(request):
    title = "Home Page"
    companyorder = OrderCompany.objects.all().count()
    individualorder = OrderIndividual.objects.all().count()
    companytrips = CompanyTrips.objects.all().count()
    individualtrips = IndividualTrips.objects.all().count()
    truckinfo = TruckInfo.objects.all().count()
    driverinfo = DriverInfo.objects.all().count()
    context = {
        "title": title,
        "truckinfo": truckinfo,
        "driverinfo": driverinfo,
        "iorder": individualorder,
        "corder": companyorder,
        "ctrips": companytrips,
        "itrips": individualtrips,

               
               
               }
    return render(request, "base/index.html", context)

templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.111.3">
    <title>{{title}}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/navbar-bottom/">
    <link rel="" href="{% static 'css/stylesheet.css' %}">
    <link rel="icon" href="{% static 'img/barbados.svg-45x45' %}" type="image/png" sizes="180x180">

    

    

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">
<meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
     {% static 'css/style.css' %}
    </style>

    
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>
    <br>
    <br><br><br><br><br>
    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>

    
    <main class="container">
        {% if messages %}
      <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</li>
            {% endfor %}
      </ul>
      {% endif %} 
        <div class="bg-body-tertiary p-5 rounded mt-6">
      {% comment %} <div class="header"> <h1>{{title}}</h1> </div> {% endcomment %}
      
      {% block content %}
          <br>
      {% endblock %}
     
    </main>
  </div>
{% include 'base/navbar.html' %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>

      
  </body>
</html>

templates/base/cnavbar.html
<a class="btn btn-outline-info" href="{% url 'orders:companyorder' %}">New Order</a>
<a class="btn btn-outline-success" href="{% url 'orders:viewcompanyorder' %}">View Order</a>
<a class="btn btn-outline-danger" href="{% url 'trips:companytrip' %}">New Trip</a>
<a class="btn btn-outline-warning" href="{% url 'trips:viewcompanytrip' %}">View Trip</a>

templates/base/dnavbar.html
<a class="btn btn-outline-info" href="{% url 'drivers:driver' %}">New Driver</a>
<a class="btn btn-outline-success" href="{% url 'drivers:displaydriver' %}">View Driver</a>
{% comment %} <a class="btn btn-outline-success" href="{% url 'driverdetails' %}">View Details</a> {% endcomment %}

templates/base/inavbar.html
<a class="btn btn-outline-info" href="{% url 'orders:individualorder' %}">New Order</a>
<a class="btn btn-outline-success" href="{% url 'orders:viewindividualorder' %}">View Order</a>
<a class="btn btn-outline-danger" href="{% url 'trips:individualtrip' %}">New Trip</a>
<a class="btn btn-outline-warning" href="{% url 'trips:viewindividualtrip' %}">View Trip</a>

templates/base/index.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<style>
  /* Customize the font and color for the links */
  .custom-link {
    font-family: Matura MT Script Capitals; /* Change to your desired font */
    color: green; /* Change to your desired color */
  }
</style>

<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title">TRUCKS</h1>
        <h2 class="card-text"><a href="{% url 'trucks:truck' %}" class="text-decoration-none custom-link">{{truckinfo}}</a></h2>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title">DRIVERS</h1>
        <h2 class="card-text"><a href="{% url 'drivers:displaydriver' %}?param_name=value" class="text-decoration-none custom-link">{{driverinfo}}</a></h2>
      </div>
    </div>
  </div>
</div>
<br>
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title">ORDERS</h1>
        <h2 class="card-text">Company Orders : <a href="{% url 'orders:viewcompanyorder' %}" class="text-decoration-none custom-link">{{corder}}</a></h2>
        <h2 class="card-text">Individual Orders : <a href="{% url 'orders:viewindividualorder' %}" class="text-decoration-none custom-link">{{iorder}}</a></h2>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title">TRIP</h1>
        <h2 class="card-text">Company Trips : <a href="{% url 'trips:viewcompanytrip' %}" class="text-decoration-none custom-link">{{ctrips}}</a></h2>
        <h2 class="card-text">Individual Trips : <a href="{% url 'trips:viewindividualtrip' %}" class="text-decoration-none custom-link">{{itrips}}</a></h2>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/base/navbar.html
{% load static %}
<nav class="navbar fixed-top navbar-expand-sm navbar-light bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'base:index' %}"><img src="{% static 'img/barbados.svg' %}" width="100" height="100"><a>


      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% comment %} <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse"> {% endcomment %}
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav">
      {% if user.is_staff %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'trucks:truck' %}">Truck</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'drivers:displaydriver' %}">Driver</a>
          </li> 
          {% comment %} <li class="nav-item">
            <a class="nav-link" href="#">Consignment</a>
          </li>  {% endcomment %}
          {% comment %} <li class="nav-item">
            <a class="nav-link" href="#">Add Category</a>
          </li> {% endcomment %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Make an Order
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'orders:viewcompanyorder' %}">Company</a></li>
              {% comment %} <li><a class="dropdown-item" href="{% url 'orders:viewindividualorder' %}">Individual</a></li> {% endcomment %}
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'orders:viewindividualorder' %}">Individual</a></li>
            </ul>
          </li>
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'account:registry' %}">Users</a>
            </li>
            {% endif %}
        </ul>
        
           {% endif %}
        <ul class="navbar-nav ml-auto">

          {% if request.user.is_authenticated %}
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:logout' %}"><button class= 'btn btn-danger'> Logout</button></a>
          </li>
          
          </ul> 
          {% endif %}
      </div>
    </div>
  </nav>
  
    
       
  

templates/base/registrynavbar.html
<a class="btn btn-outline-info" href="{% url 'account:register' %}">Add Users</a>
<a class="btn btn-outline-success" href="{% url 'account:registry' %}">View Users</a>