base/urls.py
from django.urls import path
from trips import views
from . import views
app_name="base"
urlpatterns = [
    path('', views.home, name='index'),
]

drivers/urls.py
from django.urls import path
from . import views
app_name = "drivers"
urlpatterns = [
     path('add-driver/', views.AddDriver, name='driver'),
    path('update-driver/<str:pk>/', views.UpdateDriver, name='updatedriver'),
    path('delete-driver/<str:delete>/', views.DeleteDriver, name='deletedriver'),
    path('showdrivers/', views.ViewDriver, name='displaydriver'),
    path('driverdetails/<str:pk>/', views.DriverDetails, name='driverdetails'),
]

trips/urls.py
from django.urls import path
from . import views

app_name = "trips"

urlpatterns = [
    path("add-Itrip/", views.IndividualTripForm, name="individualtrip"),
    path("view-Itrip/", views.IndividualTripView, name="viewindividualtrip"),
    path("update-Itrip/<str:pk>/", views.ITripUpdate, name="updateindividualtrip"),
    path("delete-Itrip/<str:pk>/", views.DeleteItrip, name="deleteindividualtrip"),
    path("update-Ctrip/<str:pk>/", views.CTripUpdate, name="updatecompanytrip"),
    path("add-Ctrip/", views.CompanyTripForm, name="companytrip"),
    path("view-Ctrip/", views.CompanyTripView, name="viewcompanytrip"),
    path("delete-Ctrip/<str:pk>/", views.DeleteCtrip, name="deletecompanytrip"),
    path('view-trip-corders/<str:ctrip>/', views.ctrip_order, name='ctorders'),
    path('view-trip-iorders/<str:itrip>/', views.itrip_order, name='itorders'),
    path('print-corders/<str:cprint>/', views.print_ctrip_order, name='cprint'),
    path('print-iorders/<str:iprint>/', views.print_itrip_order, name='iprint'),
    
]

trucks/urls.py
from django.urls import path
from . import views
app_name="trucks"
urlpatterns = [
    path('add-truck/', views.AddTruck, name='truck'),
    path('update-truck/<str:pk>/', views.UpdateTruck, name='updatetruck'),
    path('delete-truck/<str:delete>/', views.DeleteTruck, name='deletetruck'),
]

drivers/models.py
from django.db import models
from base.models import Name
from trucks.models import TruckInfo
# Create your models here.
class DriverInfo(Name):
    profile_pic = models.ImageField(upload_to="users/")
    assigned_truck = models.ForeignKey(TruckInfo, on_delete=models.CASCADE)
    date_joined = models.DateField(auto_now_add=True)
    date_modified = models.DateField(auto_now=True)

    class Meta:
        verbose_name = "Driver Information"
        verbose_name_plural = "Driver Informations"
        ordering = ["first_name"]

    def __str__(self):
        return f"{self.fullname.title()}"

trucks/models.py
from django.db import models

# Create your models here.
class TruckInfo(models.Model):
    bl_number = models.CharField(max_length=7)
    plate_number = models.CharField(max_length=10)

    class Meta:
        verbose_name = "Truck Informantion"
        verbose_name_plural = "Truck Information"

    def __str__(self):
        return f"{self.bl_number} {self.plate_number}"

drivers/views.py
from .models import *
from .forms import *
from django.core.paginator import Paginator
from django.contrib import messages
from django.shortcuts import render, redirect
from orders.models import *
from django.db.models.deletion import ProtectedError
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from account.decorators import admin_required

# Create your views here.


@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def AddDriver(request):
    title = "Add Driver"
    form = DriverCreate(request.POST or None, request.FILES or None)
    query = DriverInfo.objects.all()
    if request.method == "POST":
        if form.is_valid():
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            if query.filter(first_name=first_name, last_name=last_name):
                messages.error(request, "This Driver already exists")
                return redirect("drivers:driver")
            else:
                form.save()
                messages.success(request, "This Driver add successfully")
                return redirect("drivers:displaydriver")
    context = {"driverform": form, "title": title}
    return render(request, "forms/driver_form.html", context)


@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def ViewDriver(request):
    title = "View Driver"
    param_value = request.GET.get("param_name")
    queryset = DriverInfo.objects.all().order_by("id")
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    serial_numbers = list(
        range(
            (page.number - 1) * page.paginator.per_page + 1,
            min(page.number * page.paginator.per_page, page.paginator.count) + 1,
        )
    )

    # Combine serial numbers and items into a list of tuples
    items_with_serial_numbers = zip(serial_numbers, page)

    context = {
        "alldriver": queryset,
        "title": title,
        "page": page,
        "items": items_with_serial_numbers,
    }
    return render(request, "display/driver.html", context)


@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def DriverDetails(request, pk):
    title = "Driver Details"
    unique = DriverInfo.objects.get(id=pk)

    context = {"details": unique, "title": title}
    return render(request, "display/driverdetails.html", context)


@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def UpdateDriver(request, pk):
    title = "Update Driver"
    queryset = DriverInfo.objects.all()
    query = DriverInfo.objects.get(id=pk)
    update = DriverUpdate(request.POST or None, request.FILES or None, instance=query)
    if request.method == "POST":
        if update.is_valid():
            update.save()
            messages.success(request, "Update successful")
            return redirect("drivers:driverdetails", pk=pk)
    context = {"updatedriver": update, "title": title}
    return render(request, "update/driverdetails.html", context)


# handle foreignkey that is protected
@admin_required
def DeleteDriver(request, delete):
    title = "Delete Driver"
    try:
        tag = "Are you sure you want to delete this entry ?"
        query = DriverInfo.objects.get(id=delete)
        if request.method == "POST":
            query.delete()
            messages.success(request, "Successfully Deleted")
            return redirect("drivers:displaydriver")
        context = {"tags": tag, "title": title}
        return render(request, "delete/driverdelete.html", context)

    except ProtectedError as e:
        protected_references = []
        for i in e.protected_objects:
            if isinstance(i, OrderCompany):
                protected_references.append(f"{i.trip_no}")
        error_message = (
            f"This driver can't be deleted as he is used in a particular Order: "
            + ", ".join(protected_references)
        )
        context = {"msg": error_message}
        return render(request, "display/drivererror.html", context)

trips/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from orders.models import OrderCompany, OrderIndividual
from .forms import *
from orders.models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models.deletion import ProtectedError


# Create your views here.
@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def IndividualTripForm(request):
    title = "Trips"
    query = IndividualTrips.objects.all()
    iform = IndividualCreateTrips(request.POST or None, request.FILES or None)
    if request.method == "POST":
        if iform.is_valid():
            initials = iform.cleaned_data["initials"]
            if query.filter(initials=initials).exists():
                messages.error(request, "This Trip Name already exists")
                return redirect("trips:individualtrip")
            else:
                iform.save()
                messages.success(request, "New Trip added successfully")
                return redirect("trips:viewindividualtrip")
    context = {"itrip": iform, "title": title, "iadded": query}
    return render(request, "forms/itrip.html", context)


@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def IndividualTripView(request):
    title = "Trips"
    query = IndividualTrips.objects.all()

    context = {"title": title, "iadded": query}
    return render(request, "display/itrip.html", context)



@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def ITripUpdate(request, pk):
    title = "Update Trips"
    query = IndividualTrips.objects.get(id=pk)
    update = IndividualUpdateTrips(request.POST or None, instance=query)
    if request.method == "POST":
        if update.is_valid():
            update.save()
            return redirect("trips:viewindividualtrip")
        
    context = {"title": title, "trip": update}
    return render(request, "update/itrip.html", context)


def DeleteItrip(request, pk):
    title = "Delete Individual Trip"
    try:
        query = get_object_or_404(IndividualTrips, id=pk)
        tag = f"Are you sure you want to delete this trip: {query.name}/{query.id}/{query.initials}/{query.date} ?"
        if request.method == "POST":
            query.delete()
            messages.success(request,"Trip Successfully Deleted")
            return redirect("trips:viewindividualtrip")
        
        context = {"title": title, "trip": query, "tags":tag}
        return render(request, "delete/itrip.html", context)
    except ProtectedError as e:
        protected_references = []
        for i in e.protected_objects:
            if isinstance(i, OrderIndividual):
                protected_references.append(f'{i.trip_no}')
        error_message = f"This Trip can not be deleted as it is used in a particular Company Order: " + ". ".join(protected_references)
        context = {
            "msg":error_message
        }
        return render(request, 'delete/itriperror.html', context)

@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def CompanyTripForm(request):
    title = "Trips"
    queryset = CompanyTrips.objects.all()
    form = CompanyCreateTrips(request.POST or None, request.FILES or None)
    if request.method == "POST":
        if form.is_valid():
            initials = form.cleaned_data["initials"]
            if queryset.filter(initials=initials).exists():
                messages.error(request, "This Trip Name already exists")
                return redirect("trips:companytrip")
            else:
                form.save()
                messages.success(request, "New Trip added successfully")
                return redirect("trips:viewcompanytrip")
    context = {"trip": form, "title": title, "added": queryset}
    return render(request, "forms/ctrips.html", context)


@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def CompanyTripView(request):
    title = "Trips"
    queryset = CompanyTrips.objects.all()

    context = {"title": title, "added": queryset}
    return render(request, "display/ctrip.html", context)


@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def CTripUpdate(request, pk):
    title = "Update Trips"
    query = CompanyTrips.objects.get(id=pk)
    update = CompanyUpdateTrips(request.POST or None, instance=query)
    if request.method == "POST":
        if update.is_valid():
            update.save()
            messages.success(request,"Trip Successfully Updated")
            return redirect("trips:viewcompanytrip")
        
    context = {"title": title, "trip": update}
    return render(request, "update/ctrip.html", context)


def DeleteCtrip(request, pk):
    title = "Delete Company Trip"
    try:
        query = get_object_or_404(CompanyTrips, id=pk)
        tag = f"Are you sure you want to delete this trip: {query.name}/{query.id}/{query.initials}/{query.date} ?"
        if request.method == "POST":
            query.delete()
            messages.success(request,"Trip Successfully Deleted")
            return redirect("trips:viewcompanytrip")
        
        context = {"title": title, "trip": query, "tags":tag}
        return render(request, "delete/ctrip.html", context)
    except ProtectedError as e:
        protected_references = []
        for i in e.protected_objects:
            if isinstance(i, OrderCompany):
                protected_references.append(f'{i.trip_no}')
        error_message = f"This Trip can not be deleted as it is used in a particular Company Order: " + ". ".join(protected_references)
        context = {
            "msg":error_message
        }
        return render(request, 'delete/ctriperror.html', context)


def ctrip_order(request, ctrip):
    ctrip = get_object_or_404(CompanyTrips, id=ctrip)
    corder = OrderCompany.objects.filter(trip_no=ctrip)
    context ={
        'ctrip':ctrip,
        'corder':corder
    }
    return render(request, "display/viewordertrips.html", context)


def print_ctrip_order(request, cprint):
    corder = get_object_or_404(OrderCompany, id=cprint)
    context ={
        'corder':corder
    }
    return render(request, "print/cprint.html", context)


def itrip_order(request, itrip):
    itrip = get_object_or_404(IndividualTrips, id=itrip)
    iorder = OrderIndividual.objects.filter(trip_no=itrip)
    context ={
        'itrip':itrip,
        'iorder':iorder
    }
    return render(request, "display/iviewordertrips.html", context)

def print_itrip_order(request, iprint):
    iorder = get_object_or_404(OrderIndividual, id=iprint)
    context ={
        'iorder':iorder
    }
    return render(request, "print/iprint.html", context)

trucks/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from .models import *
from drivers.models import *
from .forms import *
from django.contrib import messages
from django.db.models.deletion import ProtectedError
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from account.decorators import admin_required


# Create your views here.
@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def AddTruck(request):
    title = "Add Truck"
    form = TruckCreate(request.POST or None)
    queryset = TruckInfo.objects.all().order_by("id")
    print("Queryset Length:", len(queryset))
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    serial_numbers = list(range(
        (page.number - 1) * page.paginator.per_page + 1,
        min(page.number * page.paginator.per_page, page.paginator.count) + 1
    ))

    # Combine serial numbers and items into a list of tuples
    items_with_serial_numbers = zip(serial_numbers, page)
    if request.method == "POST":
        if form.is_valid():
            bl_number = form.cleaned_data["bl_number"]
            plates = form.cleaned_data["plate_number"]
            if queryset.filter(bl_number=bl_number, plate_number=plates).exists():
                messages.error(request, "This Truck Number already exist")
                return redirect("trucks:truck")
            else:
                form.save()
            return redirect("trucks:truck")
    context = {
        "truckform": form,
        "alltruck": queryset,
        "title": title,
        "page": page,
        "items": items_with_serial_numbers,
    }
    return render(request, "forms/truckform.html", context)


@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def UpdateTruck(request, pk):
    title = "Update Truck"
    queryset = TruckInfo.objects.get(id=pk)
    update = TruckUpdate(request.POST or None, instance=queryset)
    if request.method == "POST":
        if update.is_valid():
            update.save()
            messages.success(request, "Update Successful")
            return redirect("trucks:truck")
        # else:
        #     messages.error(request, "Update Not Successful")

    context = {"updatetruck": update, "alltruck": queryset, "title": title}
    return render(request, "update/trucks.html", context)


@admin_required
def DeleteTruck(request, delete):
    title = "Delete Truck"
    tag = "Are you sure you want to delete this entry ?"
    queryset = TruckInfo.objects.get(id=delete)
    update = TruckUpdate(request.POST or None, instance=queryset)
    if request.method == "POST":
        queryset.delete()
        messages.success(request, "Successfully Deleted")
        return redirect("trucks:truck")

    context = {"updatetruck": update, "alltruck": queryset, "tags": tag, "title": title}
    return render(request, "delete/deletetruck.html", context)

templates/forms/Individualorderform.html
{% extends 'base/base.html' %} 
{% load crispy_forms_tags %} 



{% block content %}
{% include "base/inavbar.html" %} 
<form method="POST" action="">
<br>
  {% csrf_token %}
  {{ individualorder|crispy }}<br>
  <input class="btn btn-outline-primary" type="submit" value="Save" />
  <br>
</form>
{% endblock %}

templates/forms/companyorderform.html
{% extends 'base/base.html' %} 
{% load crispy_forms_tags %} 


{% block content %}
{% include "base/cnavbar.html" %}<br>
<form method="POST" action="">
<br>
  {% csrf_token %} 
  {{ companyorder|crispy }}<br>
  <input class="btn btn-outline-primary" type="submit" value="Save" />
</form>
{% endblock %}

templates/forms/ctrips.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

{% include "base/cnavbar.html" %} 
    <form method = "POST" enctype="multipart/form-data">
        {% csrf_token %}

            <br>
            {{trip|crispy}} <br>
       <input class="btn btn-outline-primary" type="submit" value="Save" />
    </form>
    <br>
    
{% endblock %}

templates/forms/driver_form.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    {% include "base/dnavbar.html" %}<br>
    <form method = "POST" enctype="multipart/form-data">
        {% csrf_token %}
            {{driverform|crispy}} <br>
        <input class="btn btn-outline-primary" type="submit" value="Save" />
    
    </form>
    
{% endblock %}

templates/forms/itrip.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

    {% include "base/inavbar.html" %}
   
    <form method = "POST" enctype="multipart/form-data">
      {% csrf_token %}

            <br>
            {{itrip|crispy}} <br>
        <input class="btn btn-outline-primary" type="submit" value="Save" />
    </form></p>
{% endblock %}

templates/forms/trip.html
{% extends 'base/base.html' %} 
{% load crispy_forms_tags %} 



{% block content %}
<form method="POST" action="">
  {% csrf_token %} 
  {{ companyorder|crispy }}<br>
  <input class="btn btn-outline-primary" type="submit" value="Save" />
</form>
{% endblock %}

templates/forms/truckform.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

    <form method = "POST">
        {% csrf_token %}
            {{truckform|crispy}} <br>
        <input class="btn btn-outline-primary" type="submit" value="Save" />
    </form>
    <br>
    <div class="table responsive">
    
         <br>
     <table class = 'table table-bordered table-striped'>
        <thead class = 'table-light'>
            <tr>
            <th class = "text-center">S/N</th>
            <th class = "text-center">TRUCK NUMBER</th>
            <th class = "text-center">PLATE NUMBER</th>
            {% if request.user.is_superuser %}
            
            <th class = "text-center">DELETE</th>
            {% endif %}
            </tr>
        </thead>
        
        {% for serial_number, item in items %}
        {% comment %} {{item.item_name}} has this quantity: {{item.quantity}}<br> {% endcomment %}
        <tr>
            <td class = "text-center">{{ serial_number }}</td>
            <td class = "text-center"><a href="{% url 'trucks:updatetruck' item.id %}">{{item.bl_number|upper}}</a></td>
            <td class = "text-center">{{item.plate_number|upper}}</td>
            {% if request.user.is_superuser %}
            <td class = "text-center"><a href="{% url 'trucks:deletetruck' item.id %}"><img src="{% static 'img/del.jpg' %}" height= "20" width="20"></a></td>
        {% endif %}
        </tr>
        {%endfor%}
        
        </table>
        
    </div>
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% if page.has_previous %}
          <li class="page-item"><a class="page-link" href="{% url 'trucks:truck' %}?page={{ page.previous_page_number }}">Previous</a></li>
        {% endif %}
        {% for i in page.paginator.page_range %}
        <li class="page-item {% if page.number == i %}active{% endif %}">
            <a class="page-link" href="{% url 'trucks:truck' %}?page={{ i }}">{{ i }}</a>
        </li>
        {% endfor %}
          {% if page.has_next %}
          <li class="page-item"><a class="page-link" href="{% url 'trucks:truck' %}?page={{ page.next_page_number }}">Next</a></li>
          {% endif %}
        </ul>
      </nav>
{% endblock %}