barbados/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls", namespace="base")),
    path("account-app/", include("account.urls", namespace="account")),
    path("truck-app/", include("trucks.urls", namespace="trucks")),
    path("driver-app/", include("drivers.urls", namespace="drivers")),
    path("order-app/", include("orders.urls", namespace="orders")),
    path("trip-app/", include("trips.urls", namespace="trips")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/urls.py
from django.urls import path
from trips import views
from . import views
app_name="base"
urlpatterns = [
    path('', views.home, name='index'),
]

orders/urls.py
from django.urls import path
from . import views

app_name="orders"
urlpatterns=[

    path('addcompanyorder/', views.AddCompanyOrder, name='companyorder'),
    path('update-companyorder/<str:pk>/', views.UpdateCompanyOrder, name='updatecompanyorder'),
    path('viewcompanyorder/', views.ViewCompanyOrder, name='viewcompanyorder'),
    path('companyorderdetails/<str:pk>/', views.CompanyOrderDetails, name='companyorderdetail'),
    path('addindividualorder/', views.AddIndivdualOrder, name='individualorder'),
    path('update-individualorder/<str:pk>/', views.UpdateIndividualOrder, name='updateindividualorder'),
    path('viewindividualorder/', views.ViewIndividualOrder, name='viewindividualorder'),
    path('individualorderdetails/<str:pk>/', views.IndividualOrderDetails, name='individualorderdetail'),
    path('idelete/<str:pk>/', views.DeleteIOrder, name='idelete'),
    path('cdelete/<str:pk>/', views.DeleteCOrder, name='cdelete'),
    
]

templates/reports/companyorderdetail.html
{% extends 'base/index.html' %} {% load crispy_forms_tags %} {% load static %}
{% block content %}
{% include "base/cnavbar.html" %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <div class="text-center">
        <img
          src="{{orderdetails.driver_info.profile_pic.url}}"
          alt="Profile Image"
          class="img-fluid rounded-circle mb-3"
          style="width: 150px; height: 150px"
        />
        <p>Driver's Name: {{orderdetails.driver_info.fullname}}</p>
        <p>ID Type: {{orderdetails.driver_info.id_type}}</p>
        <p>ID Number: {{orderdetails.driver_info.id_number}}</p>
        <p>Phone: {{orderdetails.driver_info.phone_number}}</p>
        <p>Location: City, Country</p>

        <h4>ASSIGNED VEHICLE</h4>
        <p>BL Number: {{orderdetails.driver_info.assigned_truck.bl_number}}</p>
        <p>
          Plate Number: {{orderdetails.driver_info.assigned_truck.plate_number|upper}}
        </p>
      </div>

      {% comment %}
      <div class="col-md-3"></div>
      {% endcomment %}
    </div>
    <div class="col-md-6">
      <h4>COMPANY INFORMATION</h4>
      <p>Company Name: {{orderdetails.company_name}}</p>
      <p>CAC Reg No: {{orderdetails.cac_no}}</p>
      
      <hr />

      <h4>COMPANY'S REPRESENTATIVE INFORMATION</h4>
      <p>Repsentative Name: {{orderdetails.fullname}}</p>
      <p>
        Repsentative Number: {{orderdetails.phone_number}}
      </p>

      <hr />
      <h4>CONSIGNMENT DETAILS</h4>
      <p>
        Consignment Type: {{orderdetails.con_type}}
      </p>
      <p>Weight: {{orderdetails.weight}} tons</p>
      <hr />

      <h4>LOGISTICS DETAILS</h4>
      <p>
        Take-off Location: {{orderdetails.take_off_location|title}}
      </p>
      <p>Destination: {{orderdetails.destination|title}} </p>
      <hr />
    </div>
  </div>
</div>
<div class="text-center mt-3">
  <a class="btn btn-outline-primary" href="{% url 'orders:updatecompanyorder' pk=orderdetails.pk %}">Update Order</a>
</div>

{% comment %} <script>
  document
    .getElementById("print-button")
    .addEventListener("click", function () {
      window.print();
    });
</script> {% endcomment %}

{% endblock %}

templates/reports/individualorderdetail.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
{% include "base/inavbar.html" %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <div class="text-center">
                <img src="{{orderdetails.driver_info.profile_pic.url}}" alt="Profile Image" class="img-fluid rounded-circle mb-3" style="width: 150px; height: 150px;">
                <h4>{{orderdetails.fullname}}</h4>
                <p>Location: City, Country</p>
                <p>ID Type: {{orderdetails.id_type}}</p>
                <p>ID Number: {{orderdetails.id_number}}</p>
                <p>Phone: {{orderdetails.phone_number}}</p>
           
                <h3>Assigned Vehicle</h3>
                <p>BL Number: {{orderdetails.driver_info.assigned_truck.bl_number}}</p>
                <p>Plate Number: {{orderdetails.driver_info.assigned_truck.plate_number}}</p>
                
            </div>
        </div>
        <div class="col-md-6">
                
                <h3>CLIENT INFORMATION</h3>
                <p>Full Name: {{orderdetails.fullname}}</p>
                <p>Phone Number: {{orderdetails.phone_number}}</p>
                <p>ID Type: {{orderdetails.phone_number}}</p>
            
            
            <h3>CONSIGNMENT INFORMATION</h3>
            <p>Weight of Consignment: {{orderdetails.weight}}</p>
            <p>Consignment Type: {{orderdetails.con_type}}</p>
            
            <h3>LOGISTICS INFORMATION</h3>
            <p>Take off Location: {{orderdetails.take_off_location}}</p>
            <p>Destination: {{orderdetails.destination}}</p>
            
        </div>
    </div>
</div>
<div class="text-center mt-3">
  {% comment %} <button class="btn btn-outline-warning" id="print-button">Print</button> {% endcomment %}
  <a class="btn btn-outline-primary" href="{% url 'orders:updateindividualorder' pk=orderdetails.pk %}">Update Order</a>
</div>

<script>
        document.getElementById("print-button").addEventListener("click", function() {
            window.print();
        });
    </script>

        

{% endblock %}