account/urls.py
from django.urls import path
from . import views
from .views import *
from django.contrib.auth.views import LogoutView

app_name = "account"
urlpatterns = [
    path('register/', views.Registration, name='register'),
    path('update-user/<str:pk>/', views.UpdateUser, name='updateuser'),
    path('registry/', views.UserRegistry, name='registry'),
    path('user-details/<str:pk>/', views.UserDetails, name='userdetails'),
    path('login/', CreateLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('delete-user/<str:pk>/', views.DeleteUser, name='deleteuser'),
]

barbados/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls", namespace="base")),
    path("account-app/", include("account.urls", namespace="account")),
    path("truck-app/", include("trucks.urls", namespace="trucks")),
    path("driver-app/", include("drivers.urls", namespace="drivers")),
    path("order-app/", include("orders.urls", namespace="orders")),
    path("trip-app/", include("trips.urls", namespace="trips")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/urls.py
from django.urls import path
from trips import views
from . import views
app_name="base"
urlpatterns = [
    path('', views.home, name='index'),
]

drivers/urls.py
from django.urls import path
from . import views
app_name = "drivers"
urlpatterns = [
     path('add-driver/', views.AddDriver, name='driver'),
    path('update-driver/<str:pk>/', views.UpdateDriver, name='updatedriver'),
    path('delete-driver/<str:delete>/', views.DeleteDriver, name='deletedriver'),
    path('showdrivers/', views.ViewDriver, name='displaydriver'),
    path('driverdetails/<str:pk>/', views.DriverDetails, name='driverdetails'),
]

orders/urls.py
from django.urls import path
from . import views

app_name="orders"
urlpatterns=[

    path('addcompanyorder/', views.AddCompanyOrder, name='companyorder'),
    path('update-companyorder/<str:pk>/', views.UpdateCompanyOrder, name='updatecompanyorder'),
    path('viewcompanyorder/', views.ViewCompanyOrder, name='viewcompanyorder'),
    path('companyorderdetails/<str:pk>/', views.CompanyOrderDetails, name='companyorderdetail'),
    path('addindividualorder/', views.AddIndivdualOrder, name='individualorder'),
    path('update-individualorder/<str:pk>/', views.UpdateIndividualOrder, name='updateindividualorder'),
    path('viewindividualorder/', views.ViewIndividualOrder, name='viewindividualorder'),
    path('individualorderdetails/<str:pk>/', views.IndividualOrderDetails, name='individualorderdetail'),
    path('idelete/<str:pk>/', views.DeleteIOrder, name='idelete'),
    path('cdelete/<str:pk>/', views.DeleteCOrder, name='cdelete'),
    
]

trips/urls.py
from django.urls import path
from . import views

app_name = "trips"

urlpatterns = [
    path("add-Itrip/", views.IndividualTripForm, name="individualtrip"),
    path("view-Itrip/", views.IndividualTripView, name="viewindividualtrip"),
    path("update-Itrip/<str:pk>/", views.ITripUpdate, name="updateindividualtrip"),
    path("delete-Itrip/<str:pk>/", views.DeleteItrip, name="deleteindividualtrip"),
    path("update-Ctrip/<str:pk>/", views.CTripUpdate, name="updatecompanytrip"),
    path("add-Ctrip/", views.CompanyTripForm, name="companytrip"),
    path("view-Ctrip/", views.CompanyTripView, name="viewcompanytrip"),
    path("delete-Ctrip/<str:pk>/", views.DeleteCtrip, name="deletecompanytrip"),
    path('view-trip-corders/<str:ctrip>/', views.ctrip_order, name='ctorders'),
    path('view-trip-iorders/<str:itrip>/', views.itrip_order, name='itorders'),
    path('print-corders/<str:cprint>/', views.print_ctrip_order, name='cprint'),
    path('print-iorders/<str:iprint>/', views.print_itrip_order, name='iprint'),
    
]

trucks/urls.py
from django.urls import path
from . import views
app_name="trucks"
urlpatterns = [
    path('add-truck/', views.AddTruck, name='truck'),
    path('update-truck/<str:pk>/', views.UpdateTruck, name='updatetruck'),
    path('delete-truck/<str:delete>/', views.DeleteTruck, name='deletetruck'),
]

drivers/models.py
from django.db import models
from base.models import Name
from trucks.models import TruckInfo
# Create your models here.
class DriverInfo(Name):
    profile_pic = models.ImageField(upload_to="users/")
    assigned_truck = models.ForeignKey(TruckInfo, on_delete=models.CASCADE)
    date_joined = models.DateField(auto_now_add=True)
    date_modified = models.DateField(auto_now=True)

    class Meta:
        verbose_name = "Driver Information"
        verbose_name_plural = "Driver Informations"
        ordering = ["first_name"]

    def __str__(self):
        return f"{self.fullname.title()}"

drivers/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError

class DriverCreate(forms.ModelForm):
    class Meta:
        model = DriverInfo
        fields = [
            "profile_pic",
            "first_name",
            "last_name",
            "middle_name",
            "phone_number",
            "id_type",
            "id_number",
            "assigned_truck",
        ]

    def clean(self):
        cleaned_data = super().clean()
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        middle_name = self.cleaned_data.get("middle_name")
        truck = self.cleaned_data.get("assigned_truck")
        cell = self.cleaned_data.get("phone_number")
        id_no = self.cleaned_data.get("id_number")
        driver_id = self.instance.id  # Get the ID of the driver being updated

        # Check if any other driver has the same email
        if (
            DriverInfo.objects.exclude(id=driver_id)
            .filter(first_name=first_name, last_name=last_name, middle_name=middle_name)
            .exists()
        ):
            raise forms.ValidationError(
                "The first name and last name you entered is already in use by another driver."
            )

        elif (
            DriverInfo.objects.exclude(id=driver_id)
            .filter(assigned_truck=truck)
            .exists()
        ):
            raise forms.ValidationError(
                "The assigned Truck you entered is already in use by another driver."
            )

        elif (
            DriverInfo.objects.exclude(id=driver_id).filter(phone_number=cell).exists()
        ):
            raise forms.ValidationError(
                "The phone number you entered belongs to another driver."
            )

        elif DriverInfo.objects.exclude(id=driver_id).filter(id_number=id_no).exists():
            raise forms.ValidationError(
                "The ID Number you entered belongs to another driver."
            )

        return cleaned_data
    def save(self, commit=True):
        instance = super().save(commit=False)
        # Additional logic or modifications before saving
        if commit:
            instance.save()
        return instance


class DriverUpdate(forms.ModelForm):
    class Meta:
        model = DriverInfo
        fields = [
            "profile_pic",
            "first_name",
            "last_name",
            "middle_name",
            "phone_number",
            "id_type",
            "id_number",
            "assigned_truck",
        ]

    def clean(self):
        cleaned_data = super().clean()
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        middle_name = self.cleaned_data.get("middle_name")
        truck = self.cleaned_data.get("assigned_truck")
        cell = self.cleaned_data.get("phone_number")
        id_no = self.cleaned_data.get("id_number")
        driver_id = self.instance.id  # Get the ID of the driver being updated

        # Check if any other driver has the same email
        if (
            DriverInfo.objects.exclude(id=driver_id)
            .filter(first_name=first_name, last_name=last_name, middle_name=middle_name)
            .exists()
        ):
            raise forms.ValidationError(
                "The first name and last name you entered is already in use by another driver."
            )

        elif (
            DriverInfo.objects.exclude(id=driver_id)
            .filter(assigned_truck=truck)
            .exists()
        ):
            raise forms.ValidationError(
                "The assigned Truck you entered is already in use by another driver."
            )

        elif (
            DriverInfo.objects.exclude(id=driver_id).filter(phone_number=cell).exists()
        ):
            raise forms.ValidationError(
                "The phone number you entered belongs to another driver."
            )

        elif DriverInfo.objects.exclude(id=driver_id).filter(id_number=id_no).exists():
            raise forms.ValidationError(
                "The ID Number you entered belongs to another driver."
            )

        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        # Additional logic or modifications before saving
        if commit:
            instance.save()
        return instance

drivers/views.py
from .models import *
from .forms import *
from django.core.paginator import Paginator
from django.contrib import messages
from django.shortcuts import render, redirect
from orders.models import *
from django.db.models.deletion import ProtectedError
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from account.decorators import admin_required

# Create your views here.


@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def AddDriver(request):
    title = "Add Driver"
    form = DriverCreate(request.POST or None, request.FILES or None)
    query = DriverInfo.objects.all()
    if request.method == "POST":
        if form.is_valid():
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            if query.filter(first_name=first_name, last_name=last_name):
                messages.error(request, "This Driver already exists")
                return redirect("drivers:driver")
            else:
                form.save()
                messages.success(request, "This Driver add successfully")
                return redirect("drivers:displaydriver")
    context = {"driverform": form, "title": title}
    return render(request, "forms/driver_form.html", context)


@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def ViewDriver(request):
    title = "View Driver"
    param_value = request.GET.get("param_name")
    queryset = DriverInfo.objects.all().order_by("id")
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    serial_numbers = list(
        range(
            (page.number - 1) * page.paginator.per_page + 1,
            min(page.number * page.paginator.per_page, page.paginator.count) + 1,
        )
    )

    # Combine serial numbers and items into a list of tuples
    items_with_serial_numbers = zip(serial_numbers, page)

    context = {
        "alldriver": queryset,
        "title": title,
        "page": page,
        "items": items_with_serial_numbers,
    }
    return render(request, "display/driver.html", context)


@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def DriverDetails(request, pk):
    title = "Driver Details"
    unique = DriverInfo.objects.get(id=pk)

    context = {"details": unique, "title": title}
    return render(request, "display/driverdetails.html", context)


@login_required(login_url="account:login")
@staff_member_required(login_url="base:index")
def UpdateDriver(request, pk):
    title = "Update Driver"
    queryset = DriverInfo.objects.all()
    query = DriverInfo.objects.get(id=pk)
    update = DriverUpdate(request.POST or None, request.FILES or None, instance=query)
    if request.method == "POST":
        if update.is_valid():
            update.save()
            messages.success(request, "Update successful")
            return redirect("drivers:driverdetails", pk=pk)
    context = {"updatedriver": update, "title": title}
    return render(request, "update/driverdetails.html", context)


# handle foreignkey that is protected
@admin_required
def DeleteDriver(request, delete):
    title = "Delete Driver"
    try:
        tag = "Are you sure you want to delete this entry ?"
        query = DriverInfo.objects.get(id=delete)
        if request.method == "POST":
            query.delete()
            messages.success(request, "Successfully Deleted")
            return redirect("drivers:displaydriver")
        context = {"tags": tag, "title": title}
        return render(request, "delete/driverdelete.html", context)

    except ProtectedError as e:
        protected_references = []
        for i in e.protected_objects:
            if isinstance(i, OrderCompany):
                protected_references.append(f"{i.trip_no}")
        error_message = (
            f"This driver can't be deleted as he is used in a particular Order: "
            + ", ".join(protected_references)
        )
        context = {"msg": error_message}
        return render(request, "display/drivererror.html", context)

templates/display/Companyorder.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<style>
.table td,
    .table th {
        font-size: 12px; /* Adjust the font size as needed */
    }
</style>
{% include "base/cnavbar.html" %}
<div class="table-responsive">
    
         <br>
     <table class = 'table table-bordered table-striped'>
        <thead class = 'table-light'>
            <tr>
            <th class = "text-center">S/N</th>
            <th class = "text-center">CAMPANY</th>
            <th class = "text-center">CAC NO</th>
            <th class = "text-center">ASSIGNED DRIVER</th> 
            <th class = "text-center">ORDER WEIGHT</th> 
            <th class = "text-center">TYPE OF CONSIGNMENT</th> 
            <th class = "text-center">TAKE OFF LOCATION</th> 
            <th class = "text-center">DESTINATION</th> 
            <th class = "text-center">ENTRY DATE</th>
            {% if request.user.is_superuser %}
            <th class = "text-center">DELETE</th>
            {% endif %}
            </tr>
        </thead>
        
        {% for order in vieworders %}
        {% comment %} {{item.item_name}} has this quantity: {{item.quantity}}<br> {% endcomment %}
        <tr>
            <td class = "text-center">{{forloop.counter}}</td>
            <td class = "text-center"><a href="{% url 'orders:companyorderdetail' order.id %}">{{order.company_name}}</a></td>
            <td class = "text-center">{{order.cac_no}}</td>
            <td class = "text-center">{{order.driver_info.fullname|title}}</td>
            <td class = "text-center">{{order.weight}} tons</td>
            <td class = "text-center">{{order.con_type|title}}</td>
            <td class = "text-center">{{order.take_off_location|title}}</td>
            <td class = "text-center">{{order.destination|title}}</td>
            <td class = "text-center">{{order.date_joined|date:"d-M-y"}}</td>
            {% if request.user.is_superuser %}
            <td class = "text-center"><a href="{% url 'orders:cdelete' order.id %}"><img src="{% static 'img/del.jpg' %}" height= "20" width="20"></a></td>
            {% endif %}
        </tr>
        {%endfor%}
        
        </table>
    </div>
{% endblock %}

templates/display/Individualorder.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<style>
.table td,
    .table th {
        font-size: 12px; /* Adjust the font size as needed */
    }
</style>
{% include "base/inavbar.html" %}
<div class="table-responsive">
    
         <br>
     <table class = 'table table-bordered table-striped'>
        <thead class = 'table-light'>
            <tr>
            <th class = "text-center">DATE</th>
            <th class = "text-center">CLIENT NAME</th>
            <th class = "text-center">PHONE NUMBER</th>
            <th class = "text-center">ID TYPE</th>
            <th class = "text-center">ID NUMBER</th>
            <th class = "text-center">ASSIGNED DRIVER</th> 
            <th class = "text-center">ORDER WEIGHT</th> 
            <th class = "text-center">TYPE OF CONSIGNMENT</th> 
            <th class = "text-center">TAKE OFF LOCATION</th> 
            <th class = "text-center">DESTINATION</th> 
            {% if request.user.is_superuser %}
            <th class = "text-center">DELETE</th>
            {% endif %}
            </tr>
        </thead>
        
        {% for order in vieworders %}
        {% comment %} {{item.item_name}} has this quantity: {{item.quantity}}<br> {% endcomment %}
        <tr>
            <td class = "text-center">{{order.date_added|date:"d-M-y"}}</td>
            <td class = "text-center"><a href="{% url 'orders:individualorderdetail' order.id %}">{{order.fullname}}</a></td>
            <td class = "text-center">{{order.phone_number}}</td>
            <td class = "text-center">{{order.id_type}}</td>
            <td class = "text-center">{{order.id_number}}</td>
            <td class = "text-center">{{order.driver_info.fullname|title}}</td>
            <td class = "text-center">{{order.weight}}</td>
            <td class = "text-center">{{order.con_type|title}}</td>
            <td class = "text-center">{{order.take_off_location|title}}</td>
            <td class = "text-center">{{order.destination|title}}</td>
            {% if request.user.is_superuser %}
            <td class = "text-center"><a href="{% url 'orders:idelete' order.id %}"><img src="{% static 'img/del.jpg' %}" height= "20" width="20"></td>
            {% endif %}
        </tr>
        {%endfor%}
        
        </table>
    </div>
{% endblock %}

templates/display/ctrip.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

{% include "base/cnavbar.html" %} 
    <div class="table responsive">
    
         <br>
     <table class = 'table table-bordered table-striped'>
        <thead class = 'table-light'>
            <tr>
            <th class = "text-center">S/N</th>
            <th class = "text-center">TRIP NUMBER</th>
            <th class = "text-center">PROPOSAL</th>
            <th class = "text-center">VIEW</th>
           {% if request.user.is_superuser %} 
           <th class = "text-center">DELETE</th>
           {% endif %}
            </tr>
        </thead>
        
        {%for item in added %}
        {% comment %} {{item.item_name}} has this quantity: {{item.quantity}}<br> {% endcomment %}
        <tr>
            <td class = "text-center">{{forloop.counter}}</td>
            <td class = "text-center"><a href="{% url 'trips:updatecompanytrip' item.id %}">{{item.Trip_no|upper}}</a></td>
            <td class = "text-center">{{item.proposal}}</td>
            <td class = "text-center"><a href="{% url 'trips:ctorders' item.id %}" class="btn btn-outline-success">View</a></td>
           {% if request.user.is_superuser %} 
            <td class = "text-center"><a href="{% url 'trips:deletecompanytrip' item.id %}"><img src="{% static 'img/del.jpg' %}" height= "20" width="20"></a></td>
           {% endif %}
        </tr>
        {%endfor%}
        
        </table>
    </div>
{% endblock %}

templates/display/driver.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<style>
.table td,
    .table th {
        font-size: 12px; /* Adjust the font size as needed */
    }
</style>
{% include "base/dnavbar.html" %}<br>
<div class="table-responsive">
    
         <br>
     <table class = 'table table-bordered table-striped'>
        <thead class = 'table-light'>
            <tr>
            <th class = "text-center">S/N</th>
            <th class = "text-center">DRIVER NAME</th>
            <th class = "text-center">PHONE NUMBER</th>
            <th class = "text-center">ID TYPE</th> 
            <th class = "text-center">ID NUMBER</th> 
            <th class = "text-center">TRUCK NUMBER</th> 
            <th class = "text-center">PLATES NUMBER</th>
            {% if request.user.is_superuser %} 
            <th class = "text-center">DELETE</th>
            {% endif %} 
            </tr>
        </thead>
        
        {%for serial_number, driver in items %}
        {% comment %} {{item.item_name}} has this quantity: {{item.quantity}}<br> {% endcomment %}
        <tr>
            <td class = "text-center">{{ serial_number }}</td>
            <td class = "text-center"><a href="{% url 'drivers:driverdetails' driver.id %}">{{driver.fullname|title}}</a></td>
            <td class = "text-center">{{driver.phone_number}}</td>
            <td class = "text-center">{{driver.id_type}}</td>
            <td class = "text-center">{{driver.id_number}}</td>
            <td class = "text-center">{{driver.assigned_truck.bl_number|upper}}</td>
            <td class = "text-center">{{driver.assigned_truck.plate_number|upper}}</td>
            {% if request.user.is_superuser %} 
            <td class = "text-center"><a href="{% url 'drivers:deletedriver' driver.id %}"><img src="{% static 'img/del.jpg' %}" height= "20" width="20"></td>
            {% endif %} 
        </tr>
        {%endfor%}
        
        </table>
    </div>
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% if page.has_previous %}
          <li class="page-item"><a class="page-link" href="{% url 'drivers:displaydriver' %}?page={{ page.previous_page_number }}">Previous</a></li>
        {% endif %}
        {% for i in page.paginator.page_range %}
        <li class="page-item {% if page.number == i %}active{% endif %}">
            <a class="page-link" href="{% url 'drivers:displaydriver' %}?page={{ i }}">{{ i }}</a>
        </li>
        {% endfor %}
          {% if page.has_next %}
          <li class="page-item"><a class="page-link" href="{% url 'trucks:truck' %}?page={{ page.next_page_number }}">Next</a></li>
          {% endif %}
        </ul>
      </nav>
{% endblock %}

templates/display/driverdetails.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
{% include "base/dnavbar.html" %}<br>
<div class="container mt-5">
    <div class="row">
      <div class="col-md-4">
        <div class="text-center">
        
        <img src="{{details.profile_pic.url}}" alt="Profile Image" class="img-fluid rounded-circle mb-3" style="width: 150px; height: 150px;">
          <h4>{{details.fullname}}</h4>
          <p>Location: City, Country</p>
        </div>
      </div>
      <div class="col-md-8">
        <h3>Driver's Information</h3>
        <p> ID Type: {{details.id_type}}</p>
        <p> ID Number: {{details.id_number}}</p>
        <p>Phone: {{details.phone_number}}</p>
        <h3>Assigned Vehicle</h3>
        <p>BL Number: {{details.assigned_truck.bl_number}}</p>
        <p>BL Number: {{details.assigned_truck.plate_number}}</p>
      <a class="btn btn-outline-primary" href="{% url 'drivers:updatedriver' pk=details.pk %}"> Update Driver's Information</a>
      </div>
    </div>
</div>
        

{% endblock %}

templates/display/itrip.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

{% include "base/inavbar.html" %} 
    <div class="table responsive">
    
         <br>
     <table class = 'table table-bordered table-striped'>
        <thead class = 'table-light'>
            <tr>
            <th class = "text-center">S/N</th>
            <th class = "text-center">TRIP NUMBER</th>
            <th class = "text-center">PROPOSAL</th>
            <th class = "text-center">VIEW</th>
            {% if request.user.is_superuser %}
            <th class = "text-center">DELETE</th>
            {% endif %}
            </tr>
        </thead>
        
        {%for item in iadded %}
        {% comment %} {{item.item_name}} has this quantity: {{item.quantity}}<br> {% endcomment %}
        <tr>
            <td class = "text-center">{{forloop.counter}}</td>
            <td class = "text-center"><a href="{% url 'trips:updateindividualtrip' item.id %}">{{item.Trip_no|upper}}</a></td>
            <td class = "text-center">{{item.proposal}}</td>
            <td class = "text-center"><a href="{% url 'trips:itorders' item.id %}" class="btn btn-outline-success">View</a></td>
            {% if request.user.is_superuser %}
            <td class = "text-center"><a href="{% url 'trips:deleteindividualtrip' item.id %}"><img src="{% static 'img/del.jpg' %}" height= "20" width="20"></a></td>
            {% endif %}
        </tr>
        {%endfor%}
        
        </table>
    </div>
{% endblock %}

templates/display/iviewordertrips.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

{% include "base/inavbar.html" %} 
    <div class="table responsive">
    
         <br>
     <table class = 'table table-bordered table-striped'>
        <thead class = 'table-light'>
            <tr>
            <th class = "text-center">S/N</th>
            <th class = "text-center">TRIP NO.</th>
            
            <th class = "text-center">CON TYPE</th>
            <th class = "text-center">WEIGHT</th>
            <th class = "text-center">DRIVER</th>
            <th class = "text-center">TRUCK</th>
            <th class = "text-center">VIEW</th>
          
            </tr>
        </thead>
        
        {%for i in iorder %}
        {% comment %} {{item.item_name}} has this quantity: {{item.quantity}}<br> {% endcomment %}
        <tr>
            <td class = "text-center">{{forloop.counter}}</td>
            <td class = "text-center">{{i.trip_no}}</td>
            
            <td class = "text-center">{{i.con_type}}</td>
            <td class = "text-center">{{i.weight}}</td>
            <td class = "text-center">{{i.driver_info.fullname}}</td>
            <td class = "text-center">{{i.driver_info.assigned_truck.bl_number}}</td>
            <td class = "text-center"><a href="{% url 'trips:iprint' i.id %}" class="btn btn-outline-success">Print</a></td>
            
        </tr>
        {%endfor%}
        
        </table>
    </div>
{% endblock %}

templates/display/userdetails.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
{% include "base/registrynavbar.html" %}<br>
<div class="container mt-5">
    <div class="row">
      <div class="col-md-4">
        <div class="text-center">
        
        {% comment %} <img src="{{details.profile_pic.url}}" alt="Profile Image" class="img-fluid rounded-circle mb-3" style="width: 150px; height: 150px;"> {% endcomment %}
          <h4>Email: {{details.email}}</h4>
          <h4>Username: {{details.username}}</h4>
        </div>
      </div>
      <div class="col-md-8">
        <h3>Driver's Information</h3>
        {% comment %} <p> ID Type: {{details.id_type}}</p>
        <p> ID Number: {{details.id_number}}</p>
        <p>Phone: {{details.phone_number}}</p> {% endcomment %}
        <h3>Assigned Vehicle</h3>
        {% comment %} <p>BL Number: {{details.assigned_truck.bl_number}}</p>
        <p>BL Number: {{details.assigned_truck.plate_number}}</p> {% endcomment %}
      <a class="btn btn-outline-primary" href="{% url 'account:updateuser' pk=details.pk %}">Update User Information</a>
      </div>
    </div>
</div>
        

{% endblock %}

templates/display/viewregistry.html
{% extends 'base/index.html' %} {% load crispy_forms_tags %} {% load static %}
{% block content %}

<style>
  .table td,
  .table th {
    font-size: 12px; /* Adjust the font size as needed */
  }

  .colorful-tick {
    color: yellow; /* Change the color to your preference */
}
.colorful-nottick{
    color:red;
}
</style>
{% include "base/registrynavbar.html" %}<br />
<div class="table-responsive">
  <br />
  <table class="table table-bordered table-striped">
    <thead class="table-light">
      <tr>
        <th class="text-center">S/N</th>
        <th class="text-center">USERNAME</th>
        <th class="text-center">FULL NAME</th>
        <th class="text-center">EMAIL</th>
        <th class="text-center">STAFF</th>
        <th class="text-center">ADMIN</th>
        {% if request.user.is_superuser %}
        <th class="text-center">DELETE</th>
        {% endif %}
      </tr>
    </thead>

    {%for user in registry %} {% comment %} {{item.item_name}} has this
    quantity: {{item.quantity}}<br />
    {% endcomment %}
    {% if not user.is_superuser %}
    
    <tr>
      <td class="text-center">{{forloop.counter}}</td>
      <td class="text-center">
        <a href="{% url 'account:userdetails' user.id %}">{{user.username|title}}</a>
      </td>
      <td class="text-center">
        {{user.first_name|title}} {{user.last_name|title}}
      </td>
      <td class="text-center">{{user.email|title}}</td>
      <td class="text-center">
        {% if user.is_staff %}
        <span class="colorful-tick">&#x2713;</span>
        <!-- Colorful tick symbol -->
        {% else %}<span class="colorful-tick">&#x2713;</span>
        <!-- Cross symbol -->
        {% endif %}
      </td>
      <td class="text-center">
        {% if user.is_superuser %}
        <span class="colorful-tick">&#x2713;</span>
        <!-- Colorful tick symbol -->
        {% else %} <span class="colorful-nottick">&times;</span>
        <!-- Cross symbol -->
        {% endif %}
      </td>

      {% if request.user.is_superuser %}
      <td class="text-center">
        <a href="{% url 'account:deleteuser' pk=user.pk %}"
          ><img src="{% static 'img/del.jpg' %}" height="20" width="20"
        /></a>
      </td>
        {% endif %}
    </tr>
    {% endif %}
    {%endfor%}
  </table>
</div>
{% endblock %}